### ISSUE TITLE
Can not upload image even thought using example upload file

### ISSUE THREAD

**Issue by techvsi-huynguyen** [Sylchi/keystone-graphql-client#1]
<img width="729" alt="Screenshot 2023-04-20 at 21 23 17" src="https://user-images.githubusercontent.com/113961209/233396073-776af8a6-33f5-45e2-90ed-696854122f38.png">

**Comment by Sylchi** [comment]
Are you using keystone 5? this package is not meant to be used with latest keystone version

**Comment by techvsi-huynguyen** [comment]
No I used keystone 6 but I found solution for upload image to keystone 6
